# -*- coding: utf-8 -*-

from typing import Optional, Union
from pydantic import BaseModel, ConfigDict, Field
from app.core.validator import DateStr


class ComprehensiveOutSchema(BaseModel):
    """响应模型"""
    model_config = ConfigDict(from_attributes=True)
    date: Optional[DateStr] = Field(None, description="日期")
    code: Optional[str] = Field(None, description="代码")
    name: Optional[str] = Field(None, description="名称")
    new_price: Optional[float] = Field(None, description="最新价")
    change_rate: Optional[float] = Field(None, description="涨跌幅")
    volume_ratio: Optional[float] = Field(None, description="量比")
    high_price: Optional[float] = Field(None, description="最高价")
    low_price: Optional[float] = Field(None, description="最低价")
    pre_close_price: Optional[float] = Field(None, description="昨收价")
    volume: Optional[int] = Field(None, description="成交量")
    deal_amount: Optional[int] = Field(None, description="成交额")
    turnoverrate: Optional[float] = Field(None, description="换手率")
    listing_date: Optional[DateStr] = Field(None, description="上市时间")
    industry: Optional[str] = Field(None, description="行业")
    area: Optional[str] = Field(None, description="地区")
    concept: Optional[str] = Field(None, description="概念")
    style: Optional[str] = Field(None, description="板块")


class ComprehensiveDetailSchema(ComprehensiveOutSchema):
    """详情模型"""
    is_hs300: Optional[str] = Field(None, description="沪300")
    is_sz50: Optional[str] = Field(None, description="上证50")
    is_zz500: Optional[str] = Field(None, description="中证500")
    is_zz1000: Optional[str] = Field(None, description="中证1000")
    is_cy50: Optional[str] = Field(None, description="创业板50")
    pe9: Optional[float] = Field(None, description="市盈率TTM")
    pbnewmrq: Optional[float] = Field(None, description="市净率MRQ")
    pettmdeducted: Optional[float] = Field(None, description="市盈率TTM扣非")
    ps9: Optional[float] = Field(None, description="市销率TTM")
    pcfjyxjl9: Optional[float] = Field(None, description="市现率TTM")
    predict_pe_syear: Optional[float] = Field(None, description="预测市盈率今年")
    predict_pe_nyear: Optional[float] = Field(None, description="预测市盈率明年")
    total_market_cap: Optional[int] = Field(None, description="总市值")
    free_cap: Optional[int] = Field(None, description="流通市值")
    dtsyl: Optional[float] = Field(None, description="动态市盈率")
    ycpeg: Optional[float] = Field(None, description="预测PEG")
    enterprise_value_multiple: Optional[float] = Field(
        None, description="企业价值倍数")
    basic_eps: Optional[float] = Field(None, description="每股收益")
    bvps: Optional[float] = Field(None, description="每股净资产")
    per_netcash_operate: Optional[float] = Field(None, description="每股经营现金流")
    per_fcfe: Optional[float] = Field(None, description="每股自由现金流")
    per_capital_reserve: Optional[float] = Field(None, description="每股资本公积")
    per_unassign_profit: Optional[float] = Field(None, description="每股未分配利润")
    per_surplus_reserve: Optional[float] = Field(None, description="每股盈余公积")
    per_retained_earning: Optional[float] = Field(None, description="每股留存收益")
    parent_netprofit: Optional[int] = Field(None, description="归属净利润")
    deduct_netprofit: Optional[int] = Field(None, description="扣非净利润")
    total_operate_income: Optional[int] = Field(None, description="营业总收入")
    roe_weight: Optional[float] = Field(None, description="净资产收益率ROE")
    jroa: Optional[float] = Field(None, description="总资产净利率ROA")
    roic: Optional[float] = Field(None, description="投入资本回报率ROIC")
    zxgxl: Optional[float] = Field(None, description="最新股息率")
    sale_gpr: Optional[float] = Field(None, description="毛利率")
    sale_npr: Optional[float] = Field(None, description="净利率")
    netprofit_yoy_ratio: Optional[float] = Field(None, description="净利润增长率")
    deduct_netprofit_growthrate: Optional[float] = Field(
        None, description="扣非净利润增长率")
    toi_yoy_ratio: Optional[float] = Field(None, description="营收增长率")
    netprofit_growthrate_3y: Optional[float] = Field(
        None, description="净利润3年复合增长率")
    income_growthrate_3y: Optional[float] = Field(
        None, description="营收3年复合增长率")
    predict_netprofit_ratio: Optional[float] = Field(
        None, description="预测净利润同比增长")
    predict_income_ratio: Optional[float] = Field(None, description="预测营收同比增长")
    basiceps_yoy_ratio: Optional[float] = Field(None, description="每股收益同比增长率")
    total_profit_growthrate: Optional[float] = Field(
        None, description="利润总额同比增长率")
    operate_profit_growthrate: Optional[float] = Field(
        None, description="营业利润同比增长率")
    debt_asset_ratio: Optional[float] = Field(None, description="资产负债率")
    equity_ratio: Optional[float] = Field(None, description="产权比率")
    equity_multiplier: Optional[float] = Field(None, description="权益乘数")
    current_ratio: Optional[float] = Field(None, description="流动比率")
    speed_ratio: Optional[float] = Field(None, description="速动比率")
    total_shares: Optional[int] = Field(None, description="总股本")
    free_shares: Optional[int] = Field(None, description="流通股本")
    holder_newest: Optional[int] = Field(None, description="最新股东户数")
    holder_ratio: Optional[float] = Field(None, description="股东户数增长率")
    hold_amount: Optional[float] = Field(None, description="户均持股金额")
    avg_hold_num: Optional[float] = Field(None, description="户均持股数量")
    holdnum_growthrate_3q: Optional[float] = Field(
        None, description="户均持股数季度增长率")
    holdnum_growthrate_hy: Optional[float] = Field(
        None, description="户均持股数半年增长率")
    hold_ratio_count: Optional[float] = Field(None, description="十大股东持股比例合计")
    free_hold_ratio: Optional[float] = Field(None, description="十大流通股东比例合计")
    macd_golden_fork: Optional[bool] = Field(None, description="MACD金叉日线")
    macd_golden_forkz: Optional[bool] = Field(None, description="MACD金叉周线")
    macd_golden_forky: Optional[bool] = Field(None, description="MACD金叉月线")
    kdj_golden_fork: Optional[bool] = Field(None, description="KDJ金叉日线")
    kdj_golden_forkz: Optional[bool] = Field(None, description="KDJ金叉周线")
    kdj_golden_forky: Optional[bool] = Field(None, description="KDJ金叉月线")
    break_through: Optional[bool] = Field(None, description="放量突破")
    low_funds_inflow: Optional[bool] = Field(None, description="低位资金净流入")
    high_funds_outflow: Optional[bool] = Field(None, description="高位资金净流出")
    breakup_ma_5days: Optional[bool] = Field(None, description="向上突破均线5日")
    breakup_ma_10days: Optional[bool] = Field(None, description="向上突破均线10日")
    breakup_ma_20days: Optional[bool] = Field(None, description="向上突破均线20日")
    breakup_ma_30days: Optional[bool] = Field(None, description="向上突破均线30日")
    breakup_ma_60days: Optional[bool] = Field(None, description="向上突破均线60日")
    long_avg_array: Optional[bool] = Field(None, description="均线多头排列")
    short_avg_array: Optional[bool] = Field(None, description="均线空头排列")
    upper_large_volume: Optional[bool] = Field(None, description="连涨放量")
    down_narrow_volume: Optional[bool] = Field(None, description="下跌无量")
    one_dayang_line: Optional[bool] = Field(None, description="一根大阳线")
    two_dayang_lines: Optional[bool] = Field(None, description="两根大阳线")
    rise_sun: Optional[bool] = Field(None, description="旭日东升")
    power_fulgun: Optional[bool] = Field(None, description="强势多方炮")
    restore_justice: Optional[bool] = Field(None, description="拨云见日")
    down_7days: Optional[bool] = Field(None, description="七仙女下凡(七连阴)")
    upper_8days: Optional[bool] = Field(None, description="八仙过海(八连阳)")
    upper_9days: Optional[bool] = Field(None, description="九阳神功(九连阳)")
    upper_4days: Optional[bool] = Field(None, description="四串阳")
    heaven_rule: Optional[bool] = Field(None, description="天量法则")
    upside_volume: Optional[bool] = Field(None, description="放量上攻")
    bearish_engulfing: Optional[bool] = Field(None, description="穿头破脚")
    reversing_hammer: Optional[bool] = Field(None, description="倒转锤头")
    shooting_star: Optional[bool] = Field(None, description="射击之星")
    evening_star: Optional[bool] = Field(None, description="黄昏之星")
    first_dawn: Optional[bool] = Field(None, description="曙光初现")
    pregnant: Optional[bool] = Field(None, description="身怀六甲")
    black_cloud_tops: Optional[bool] = Field(None, description="乌云盖顶")
    morning_star: Optional[bool] = Field(None, description="早晨之星")
    narrow_finish: Optional[bool] = Field(None, description="窄幅整理")
    limited_lift_f6m: Optional[bool] = Field(None, description="限售解禁未来半年")
    limited_lift_f1y: Optional[bool] = Field(None, description="限售解禁未来1年")
    limited_lift_6m: Optional[bool] = Field(None, description="限售解禁近半年")
    limited_lift_1y: Optional[bool] = Field(None, description="限售解禁近1年")
    directional_seo_1m: Optional[bool] = Field(None, description="定向增发近1个月")
    directional_seo_3m: Optional[bool] = Field(None, description="定向增发近3个月")
    directional_seo_6m: Optional[bool] = Field(None, description="定向增发近6个月")
    directional_seo_1y: Optional[bool] = Field(None, description="定向增发近1年")
    recapitalize_1m: Optional[bool] = Field(None, description="资产重组近1个月")
    recapitalize_3m: Optional[bool] = Field(None, description="资产重组近3个月")
    recapitalize_6m: Optional[bool] = Field(None, description="资产重组近6个月")
    recapitalize_1y: Optional[bool] = Field(None, description="资产重组近1年")
    equity_pledge_1m: Optional[bool] = Field(None, description="股权质押近1个月")
    equity_pledge_3m: Optional[bool] = Field(None, description="股权质押近3个月")
    equity_pledge_6m: Optional[bool] = Field(None, description="股权质押近6个月")
    equity_pledge_1y: Optional[bool] = Field(None, description="股权质押近1年")
    pledge_ratio: Optional[float] = Field(None, description="质押比例")
    goodwill_scale: Optional[int] = Field(None, description="商誉规模")
    goodwill_assets_ratro: Optional[float] = Field(
        None, description="商誉占净资产比例")
    predict_type: Optional[str] = Field(None, description="业绩预告")
    par_dividend_pretax: Optional[float] = Field(None, description="每股股利税前")
    par_dividend: Optional[float] = Field(None, description="每股红股")
    par_it_equity: Optional[float] = Field(None, description="每股转增股本")
    holder_change_3m: Optional[float] = Field(None, description="近3月股东增减比例")
    executive_change_3m: Optional[float] = Field(None, description="近3月高管增减比例")
    org_survey_3m: Optional[int] = Field(None, description="近3月机构调研")
    org_rating: Optional[str] = Field(None, description="机构评级")
    allcorp_num: Optional[int] = Field(None, description="机构持股家数合计")
    allcorp_fund_num: Optional[int] = Field(None, description="基金持股家数")
    allcorp_qs_num: Optional[int] = Field(None, description="券商持股家数")
    allcorp_qfii_num: Optional[int] = Field(None, description="QFII持股家数")
    allcorp_bx_num: Optional[int] = Field(None, description="保险公司持股家数")
    allcorp_sb_num: Optional[int] = Field(None, description="社保持股家数")
    allcorp_xt_num: Optional[int] = Field(None, description="信托公司持股家数")
    allcorp_ratio: Optional[float] = Field(None, description="机构持股比例合计")
    allcorp_fund_ratio: Optional[float] = Field(None, description="基金持股比例")
    allcorp_qs_ratio: Optional[float] = Field(None, description="券商持股比例")
    allcorp_qfii_ratio: Optional[float] = Field(None, description="QFII持股比例")
    allcorp_bx_ratio: Optional[float] = Field(None, description="保险公司持股比例")
    allcorp_sb_ratio: Optional[float] = Field(None, description="社保持股比例")
    allcorp_xt_ratio: Optional[float] = Field(None, description="信托公司持股比例")
    popularity_rank: Optional[int] = Field(None, description="股吧人气排名")
    rank_change: Optional[int] = Field(None, description="人气排名变化")
    upp_days: Optional[int] = Field(None, description="人气排名连涨")
    down_days: Optional[int] = Field(None, description="人气排名连跌")
    new_high: Optional[int] = Field(None, description="人气排名创新高")
    new_down: Optional[int] = Field(None, description="人气排名创新低")
    newfans_ratio: Optional[float] = Field(None, description="新晋粉丝占比")
    bigfans_ratio: Optional[float] = Field(None, description="铁杆粉丝占比")
    concern_rank_7days: Optional[int] = Field(None, description="7日关注排名")
    browse_rank: Optional[int] = Field(None, description="今日浏览排名")
    amplitude: Optional[float] = Field(None, description="振幅")
    is_issue_break: Optional[bool] = Field(None, description="破发股票")
    is_bps_break: Optional[bool] = Field(None, description="破净股票")
    now_newhigh: Optional[bool] = Field(None, description="今日创历史新高")
    now_newlow: Optional[bool] = Field(None, description="今日创历史新低")
    high_recent_3days: Optional[bool] = Field(None, description="近期创历史新高近3日")
    high_recent_5days: Optional[bool] = Field(None, description="近期创历史新高近5日")
    high_recent_10days: Optional[bool] = Field(None, description="近期创历史新高近10日")
    high_recent_20days: Optional[bool] = Field(None, description="近期创历史新高近20日")
    high_recent_30days: Optional[bool] = Field(None, description="近期创历史新高近30日")
    low_recent_3days: Optional[bool] = Field(None, description="近期创历史新低近3日")
    low_recent_5days: Optional[bool] = Field(None, description="近期创历史新低近5日")
    low_recent_10days: Optional[bool] = Field(None, description="近期创历史新低近10日")
    low_recent_20days: Optional[bool] = Field(None, description="近期创历史新低近20日")
    low_recent_30days: Optional[bool] = Field(None, description="近期创历史新低近30日")
    win_market_3days: Optional[bool] = Field(None, description="近期跑赢大盘近3日")
    win_market_5days: Optional[bool] = Field(None, description="近期跑赢大盘近5日")
    win_market_10days: Optional[bool] = Field(None, description="近期跑赢大盘近10日")
    win_market_20days: Optional[bool] = Field(None, description="近期跑赢大盘近20日")
    win_market_30days: Optional[bool] = Field(None, description="近期跑赢大盘近30日")
    net_inflow: Optional[float] = Field(None, description="当日净流入额")
    netinflow_3days: Optional[int] = Field(None, description="3日主力净流入")
    netinflow_5days: Optional[int] = Field(None, description="5日主力净流入")
    nowinterst_ratio: Optional[int] = Field(None, description="当日增仓占比")
    nowinterst_ratio_3d: Optional[float] = Field(None, description="3日增仓占比")
    nowinterst_ratio_5d: Optional[float] = Field(None, description="5日增仓占比")
    ddx: Optional[float] = Field(None, description="当日DDX")
    ddx_3d: Optional[float] = Field(None, description="3日DDX")
    ddx_5d: Optional[float] = Field(None, description="5日DDX")
    ddx_red_10d: Optional[int] = Field(None, description="10日内DDX飘红天数")
    changerate_3days: Optional[float] = Field(None, description="3日涨跌幅")
    changerate_5days: Optional[float] = Field(None, description="5日涨跌幅")
    changerate_10days: Optional[float] = Field(None, description="10日涨跌幅")
    changerate_ty: Optional[float] = Field(None, description="今年以来涨跌幅")
    upnday: Optional[int] = Field(None, description="连涨天数")
    downnday: Optional[int] = Field(None, description="连跌天数")
    listing_yield_year: Optional[float] = Field(None, description="上市以来年化收益率")
    listing_volatility_year: Optional[float] = Field(
        None, description="上市以来年化波动率")
    mutual_netbuy_amt: Optional[int] = Field(None, description="沪深股通净买入金额")
    hold_ratio: Optional[float] = Field(None, description="沪深股通持股比例")
    secucode: Optional[str] = Field(None, description="全代码")




class ComprehensiveCreateSchema(BaseModel):
    """新增模型"""
    pass


class ComprehensiveUpdateSchema(BaseModel):
    """更新模型"""
    pass
